export enum UsersErrorCode {
  USERS_OBJECT_STORAGE_NOT_CONFIGURED = 'USERS_OBJECT_STORAGE_NOT_CONFIGURED',
  USERS_PROFILE_IMAGE_NOT_UPLOADED = 'USERS_PROFILE_IMAGE_NOT_UPLOADED',
  USERS_PROFILE_IMAGE_SIZE_MISMATCH = 'USERS_PROFILE_IMAGE_SIZE_MISMATCH',
  USERS_PROFILE_IMAGE_CONTENT_TYPE_MISMATCH = 'USERS_PROFILE_IMAGE_CONTENT_TYPE_MISMATCH',
}
